package io.github.some_example_name;

import java.util.EnumSet;

public enum tileType {
    DIRT, SAND, OCEAN, RIVER, LAND,
    ELEVATION_UP, ELEVATION_DOWN, // up & down only used for button functions
    UNOCCUPIED, EXTENSION, ROAD, BRIDGE, TUNNEL,
    SHACK, FARMHOUSE, SHOME, TRAILERPARK, BHOME, HOMEWBACK, TOWNHOUSE, HOTEL, APARTMENT, VILLA, MANSION, FIRSTRES,
    CONVSTORE, FASTFOOD, CLOTHING, GROCERY, FURNITURE, SALON, CAFE, TOY, RESTAURANT, JEWELRY, STRIPMALL, TECHNOLOGY,
    CROPS, WELL, LIVESTOCK, ENERGY, FACTORY, QUARRY, WASTE, EMERG, OFFICES, GREENHOUSES, JAIL, HOSPITAL,
    CHURCH, PARK, COMMCENT, LIBRARY, TSQUARE, CINEMA, SCHOOL, NATURET, SPORTSC, CITYHALL, FESTIVALG, STADIUM;

    public static final EnumSet<tileType> tileLandType = EnumSet.of(DIRT, SAND, OCEAN, RIVER, LAND);
    public static final EnumSet<tileType> tileOccupationType = EnumSet.of(UNOCCUPIED, EXTENSION, ROAD, BRIDGE, TUNNEL,
            SHACK, FARMHOUSE, SHOME, TRAILERPARK, BHOME, HOMEWBACK, TOWNHOUSE, HOTEL, APARTMENT, VILLA, MANSION, FIRSTRES,
            CONVSTORE, FASTFOOD, CLOTHING, GROCERY, FURNITURE, SALON, CAFE, TOY, RESTAURANT, JEWELRY, STRIPMALL, TECHNOLOGY,
            CROPS, WELL, LIVESTOCK, ENERGY, FACTORY, QUARRY, WASTE, EMERG, OFFICES, GREENHOUSES, JAIL, HOSPITAL,
            CHURCH, PARK, COMMCENT, LIBRARY, TSQUARE, CINEMA, SCHOOL, NATURET, SPORTSC, CITYHALL, FESTIVALG, STADIUM);

    public static final EnumSet<tileType> tileBuildingType = EnumSet.of(
            SHACK, FARMHOUSE, SHOME, TRAILERPARK, BHOME, HOMEWBACK, TOWNHOUSE, HOTEL, APARTMENT, VILLA, MANSION, FIRSTRES,
            CONVSTORE, FASTFOOD, CLOTHING, GROCERY, FURNITURE, SALON, CAFE, TOY, RESTAURANT, JEWELRY, STRIPMALL, TECHNOLOGY,
            CROPS, WELL, LIVESTOCK, ENERGY, FACTORY, QUARRY, WASTE, EMERG, OFFICES, GREENHOUSES, JAIL, HOSPITAL,
            CHURCH, PARK, COMMCENT, LIBRARY, TSQUARE, CINEMA, SCHOOL, NATURET, SPORTSC, CITYHALL, FESTIVALG, STADIUM);

    public static final EnumSet<tileType> oneByOneBuildingType = EnumSet.of(SHACK, SHOME, BHOME, CONVSTORE, FASTFOOD, SALON, JEWELRY, TECHNOLOGY, CROPS);
    public static final EnumSet<tileType> twoByOneBuildingType = EnumSet.of(FARMHOUSE, HOMEWBACK, TOWNHOUSE, CLOTHING, CAFE, TOY, WELL, LIVESTOCK, ENERGY, CHURCH, PARK, COMMCENT, LIBRARY, CINEMA);
    public static final EnumSet<tileType> twoByTwoBuildingType = EnumSet.of(TRAILERPARK, HOTEL, VILLA, MANSION, GROCERY, FURNITURE, RESTAURANT, FACTORY, QUARRY, WASTE, EMERG, GREENHOUSES, TSQUARE, SCHOOL, SPORTSC, CITYHALL);
    public static final EnumSet<tileType> fourByTwoBuildingType = EnumSet.of(APARTMENT, FIRSTRES, STRIPMALL, OFFICES, JAIL, HOSPITAL, NATURET, FESTIVALG, STADIUM);
    }